### ISSUE TITLE
Celsius doesn't convert to Fahrenheit despite selecting this in the settings.

### ISSUE THREAD

**Issue by katosalt** [amit9838/mousam#135]
When navigating to preferences and selecting IMPERIAL system.  No changes are actually done.  Current,  hourly and feels like all still display in Celsius.

**Comment by amit9838** [comment]
how often do you face this issue?

**Comment by katosalt** [comment]
Every time. Going back into settings reveals Celsius is still selected. Seems like the Fahrenheit setting doesn’t save for some reason. Other settings do seem to work, however.

**Comment by amit9838** [comment]
can you try reinstalling the app, make sure sure to clear the data before you install again.

**Comment by katosalt** [comment]
I tried that when I saw there was a new version. How do I clear the data?

**Comment by amit9838** [comment]
If you are using the flatpak version then hopefully you should see the prompt to clear the data when uninstalling from the software center.
Otherwise you'll have to clear it manually, for this you'll need to check where it stores the app data.
If you are not able to find the sol, pls provide distro info we'll help you out.

**Comment by katosalt** [comment]
I’m using Software Updater on Ubuntu 22.04.1. Any assistance to clear the data manually would be greatly appreciated. Thanks again!

**Comment by soumyaDghosh** [comment]
Please run this,

```
sudo snap remove --purge mausam
```
The `--purge` will clear the app data
