### ISSUE TITLE
Start with a welcome screen

### ISSUE THREAD

**Issue by forteller** [amit9838/mousam#156]
Hi. This is a really great looking project. Thanks for creating and sharing it!

I think it would be even better if instead of starting with a city, and then making you look for the button to change that, it rather started with a welcome screen asking you which one or more cities you want to add. There are quite a few Gnome apps these days that has some kind of welcome screen like that. Here's some examples:

![image](https://github.com/user-attachments/assets/cc33d931-898f-4b17-bb3b-d9031d5009ea)
![image](https://github.com/user-attachments/assets/2639d9fc-2b1f-47cb-873e-9a076850844f)
![image](https://github.com/user-attachments/assets/ba81bd02-fd34-4dad-b688-b72d950f7460)

If on first (and only first, or until you set at least one city) run of Mousam you're presented with a screen like this, with a text box to enter the name of a city and two buttons, one for add another city and one for Ok, I think that would be really cool!

Alternatively it might be easier to start with making the welcome screen just have a button to open the existing "add a city" box.

What do you think?

Thanks! :)

**Comment by amit9838** [comment]
First of all thanks for using mousam 🙂 .
Yes I also thought about this, but I preferred to work on the functionality first. Since it has been very long since the app was  launched so I believe Welcome screen it must. 
Currently I'm a bit busy in my full time job and some personal stuff.
Since it is simple to implement I'll leave this to community to have try. Will leave this issue opened for 2 weeks.
And if the issue is unresolved after 2 weeks i'll do this.

**Comment by amit9838** [comment]
/added
https://github.com/amit9838/mousam/commit/52a859c762a5d0e30449b1691b58c04d9b4f3bb3
