### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by forteller** [amit9838/mousam#157]
Hi again, just a few typos I've noticed:

There should be a space after the , in the location: "City, Country". This typo is present both in the main window and in the Locations window.

Under Show precipitation in inch it says "This option better works…", I think this should be "This option works better…"

There should be a space between the number and "km/h" under Wind. But on the other hand, the space between the number and "%" under Humidity feels too great?

Also, a few similar things:

In preferences it looks strange with "METRIC" and "IMPERIAL" in all caps. As I said in #93 I think this info should be taken from the system, and so this option might not be needed at all, but if you think it is I would suggest changing the headers to "Metric" and "Imperial" and remove the "X system with units like" from the description, so it just says "Celsius, km/h …" and "Fahrenheit, mph, …"

I think "Feels Like" should be "Feels like", and I don't see the need for the dot between that and the degree – anyways it looks like there's a bigger gap between the dot and the degree than there is between the "Feels Like" and the dot.

I don't really see the need to have the present time within the circle under Sunrise & Sunset? But if you think it should stay, I think it should probably be centered within the circle? But I feel like since it's straight below the Horizon line, it might be interpreted as being the time of sunrise?

Just some suggestions :)

Thanks!

**Comment by amit9838** [comment]
Thanks these are pretty good suggestions.
- [ ]  For city,country I'll style this on the main screen so that it will look good, but I think its a good idea to add space in this locations list,  which will require some extra logic to handle.
- [ ]  Will update the typo "This option works better…".
- [ ] About the spacing in the unit km/h and the %.  will see if we can have some spacing with the main value.
- [ ]  Will fix the typo "Feels like".
- [ ] If you see the app, It's  visualization preference is higher then standards,  that's why i preferred to use very common way to distinguish like user will perceive C/F quicker than metric/imperial (Let's see of we get some more suggestions on this).
- [ ] Current time shows local time of the selected region, so it is useful when selection other then your current location/timezone, about styling, i'll see if there is any room of improvement.

NOTE:  If user selects fonts with non-standard letter spacing he may get different alignment or spacing issues.

**Comment by amit9838** [comment]
<img width="410" alt="Screenshot 2024-09-08 at 10 41 24 AM" src="https://github.com/user-attachments/assets/7b74eb89-cc21-43ce-b36c-40d4af4ec97a">

**Comment by forteller** [comment]
That looks good! :)
